apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
data:
  slack-token: eG94Yi03MTY4ODMzNzQxMDQyLTcyMDEwMTc5MTUzMzMtT1d4empPUWRrVVNsZHJ2UmVJSm54U2dDCg==
type: Opaque
